### PR TITLE
Added Documentation for Switch Example

### PR DESCRIPTION
**Pull request by LearningMonkey61**
Created a new folder named docs and added switch.md, changing all the links as directed.

### CODE REVIEW

**Review by sagar-jadhav — CHANGES_REQUESTED** [review]
- Move Switch.md in root directory (/) and not in `/docs`
- We don't want a separate `/docs` directory
- Update README accordingly
 
Code snippet in switch.md belongs to Hello-world.go & not to Switch.go. Change the code snippet

**Comment by sagar-jadhav** [comment]
Linking with #57

**Review by sagar-jadhav — CHANGES_REQUESTED** [review]
Add link to `switch.md` in README as `./switch.html`

**Review by rajkumarGosavi — CHANGES_REQUESTED** [review]
Please add details of switch example

**Comment by sagar-jadhav** [comment]
@LearningMonkey61 Can you please have a look on review comments? & Incorporate necessary changes.

**Comment by LearningMonkey61** [comment]
Okay, I am going to take review comments into consideration.

**Review by rajkumarGosavi — APPROVED** [review]

**Comment by sagar-jadhav** [comment]
@LearningMonkey61 Content of `switch.md` has content of `hello-world.md` Can you please update documentation and add content related to `switch.go`

Please try to close this as early as possible.

Let me know if you require any help from our side.

**Comment by sagar-jadhav** [comment]
Closing #63 due to inactivity. @LearningMonkey61 Create separate PR once you are ready with your changes.

**Pull request closed without merging**
