### PR TITLE
Add HTTP server example

### PR DESCRIPTION
**Pull request by davidkroell**
This example shows how to implement a simple HTTP server in Go.

### CODE REVIEW

**Review by sagar-jadhav — CHANGES_REQUESTED** [review]
Thank you @davidkroell for contribution 👍 

Please find below review comments:
- Add description about program as comments. 
- Implement CRUD operations
- No need to use database. Perform CRUD operation over in-memory collection

**Review by rajkumarGosavi — APPROVED** [review]

**Comment by davidkroell** [comment]
alright, working on this!

**Comment by sagar-jadhav** [comment]
> alright, working on this!

Do you want me to create separate issue for this? If Yes I'll create new issue and then you can work on that and I'll merge this one.

**Comment by davidkroell** [comment]
Hi @sagar-jadhav CRUD operations are now ready for review.
Documentation is coming soon (maybe in another PR)

**Comment by sagar-jadhav** [comment]
> Hi @sagar-jadhav CRUD operations are now ready for review.
> Documentation is coming soon (maybe in another PR)

Appreciable work 👍 Changes looks good to me. 

Please add link to `http_srv.go` in **README** along with documentation in separate PR.

**Review by sagar-jadhav — APPROVED** [review]

**Review by rajkumarGosavi — COMMENTED** [review]
Great

**Pull request merged**
