### PR TITLE
adding simple-calculator doc

### LINKED ISSUE #53: Add Document for Simple Calculator Program
Refer below commits:
- [Commit 1](https://github.com/sagar-jadhav/go-examples/commit/1522697baa28bae38b964307b1adc353ff3eab20)
- [Commit 2](https://github.com/sagar-jadhav/go-examples/commit/1522697baa28bae38b964307b1adc353ff3eab20)
- [Commit 3](https://github.com/sagar-jadhav/go-examples/commit/f47deddb11788383563ff439008bf37f333e92bd)

### PR DESCRIPTION
**Pull request by komish**
Fixes #53. Thanks for participating in Hacktoberfest 2019!

### CODE REVIEW

**Review by sagar-jadhav — CHANGES_REQUESTED** [review]
Please update link to `simple-calculator.md` in **README** as `./simple-calculator.html`

**Comment by sagar-jadhav** [comment]
@komish Thank you for Contribution 👍

**Comment by komish** [comment]
@sagar-jadhav Done. Please let me know if I can help with anything else.

**Review by sagar-jadhav — APPROVED** [review]

**Comment by sagar-jadhav** [comment]
> @sagar-jadhav Done. Please let me know if I can help with anything else.

Sure @komish there are  couple of `documentation` issues that you can have a look depending on your interest.

**Issues:** #50, #46

**Comment by komish** [comment]
@sagar-jadhav I'll browse around as time allows, thanks! I want to make sure and give other hacktoberfesters some time to contribute as well.

**Comment by sagar-jadhav** [comment]
> @sagar-jadhav I'll browse around as time allows, thanks! I want to make sure and give other hacktoberfesters some time to contribute as well.

I completely agree with your point 👍

**Pull request merged**
