### PR TITLE
Create example_of_panic_and_defer.go

### PR DESCRIPTION
**Pull request by DGKSK8LIFE**
## Description

Fixes # 2 (issue)

### CODE REVIEW

**Comment by sagar-jadhav** [comment]
Linking with #2

**Comment by sagar-jadhav** [comment]
Thank you @DGKSK8LIFE for contribution.

Add general comments in your code for more description.

@aprabhat @rajkumarGosavi  please review example.

**Comment by DGKSK8LIFE** [comment]
> Add general comments in your code for more description.
added comments

**Review by rajkumarGosavi — COMMENTED** [review]
Can you also add an example using defer and panic together
`defer panic .....` something like this

**Comment by DGKSK8LIFE** [comment]
> Can you also add an example using defer and panic together
> `defer panic .....` something like this

When would you ever want to inevitably throw an error?

**Comment by rajkumarGosavi** [comment]
if you want perform some house cleaning, or call some other function before error is called

**Comment by DGKSK8LIFE** [comment]
Could you just merge my commits? I can’t think of a code example where I’d `defer panic`.

**Comment by DGKSK8LIFE** [comment]
thank you

**Pull request merged**
